/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdad8",
        "surface-variant": "#353534",
        "tertiary-container": "#e36c6c",
        "primary": "#5ddda1",
        "secondary": "#b9c7e4",
        "on-tertiary-container": "#5a030f",
        "on-primary-container": "#00311d",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#abb9d6",
        "on-surface-variant": "#bccabf",
        "inverse-primary": "#006c46",
        "error": "#ffb4ab",
        "on-secondary": "#233148",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "surface": "#131313",
        "on-tertiary": "#640c15",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#5ddda1",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#410007",
        "secondary-container": "#3c4962",
        "surface-tint": "#5ddda1",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#832429",
        "secondary-fixed": "#d6e3ff",
        "outline": "#86948a",
        "on-error": "#690005",
        "background": "#131313",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#0d1c32",
        "tertiary": "#ffb3b1",
        "on-primary-fixed-variant": "#005234",
        "primary-container": "#08a56e",
        "outline-variant": "#3d4a41",
        "tertiary-fixed-dim": "#ffb3b1",
        "surface-dim": "#131313",
        "on-secondary-fixed-variant": "#39475f",
        "primary-fixed": "#7bfabb",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#b9c7e4",
        "on-primary-fixed": "#002112",
        "on-primary": "#003823",
        "surface-container-highest": "#353534",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
